### ISSUE TITLE
merge_bn.py AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'

### ISSUE THREAD

**Issue by MichaelQWang** [ahangchen/windy-afternoon#16]
Hi ahangchen,
I install ncs(https://github.com/movidius/ncsdk),the ssd-caffe path is /opt/movidius/ssd-caffe/.
When i run merge_bn.py file,it's output is AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'.how to tackle this problem?
Thanks in advance.

#####################################
I0526 14:59:43.139652 7526 net.cpp:228] conv3 does not need backward computation.
I0526 14:59:43.139660 7526 net.cpp:228] conv3/dw/relu does not need backward computation.
I0526 14:59:43.139668 7526 net.cpp:228] conv3/dw does not need backward computation.
I0526 14:59:43.139673 7526 net.cpp:228] conv2/relu does not need backward computation.
I0526 14:59:43.139681 7526 net.cpp:228] conv2 does not need backward computation.
I0526 14:59:43.139706 7526 net.cpp:228] conv2/dw/relu does not need backward computation.
I0526 14:59:43.139744 7526 net.cpp:228] conv2/dw does not need backward computation.
I0526 14:59:43.139750 7526 net.cpp:228] conv1/relu does not need backward computation.
I0526 14:59:43.139756 7526 net.cpp:228] conv1 does not need backward computation.
I0526 14:59:43.139761 7526 net.cpp:228] conv1/dw/relu does not need backward computation.
I0526 14:59:43.139766 7526 net.cpp:228] conv1/dw does not need backward computation.
I0526 14:59:43.139771 7526 net.cpp:228] conv0/relu does not need backward computation.
I0526 14:59:43.139776 7526 net.cpp:228] conv0 does not need backward computation.
I0526 14:59:43.139782 7526 net.cpp:228] data_input_0_split does not need backward computation.
I0526 14:59:43.139787 7526 net.cpp:228] input does not need backward computation.
I0526 14:59:43.139792 7526 net.cpp:270] This network produces output detection_out
I0526 14:59:43.139940 7526 net.cpp:283] Network initialization done.
Traceback (most recent call last):
File "merge_bn.py", line 62, in 
merge_bn(net, net_deploy)
File "merge_bn.py", line 21, in merge_bn
for key in net.params.iterkeys():
AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'
michael@ubt1604:~/workspace/MobileNet-SSD$

**Comment by ahangchen** [comment]
I guess you are using python3 which is supported by NCS, but MobileNet-SSD are written in python2. You need to modify MobileNet-SSD code to make it pass training and test in python3.

**Comment by MichaelQWang** [comment]
Hi ahangchen,
Thanks for your reply.
how do you run merge_bn.py,use python2 or python3 in your project?and what MobileNet-SSD code i should modify?
Thanks in advance.

**Comment by MichaelQWang** [comment]
Hi ahangchen,
Thanks very much.You help me to tackle the problem.
Thanks again.
