### ISSUE TITLE
通过您的方式修改bug已经行不通了

### ISSUE THREAD

**Issue by qingshutie** [ahangchen/windy-afternoon#17]
您好，我也遇到了NCSDK build graph的BUG，通过您文中说的修改SDK代码中的/usr/local/bin/ncsdk/Models/NetworkStage.py，在第85行后面添加：

if ''_new' in name:
    self.alias.append(name[:-4])
首先会报错格式错误，然后我改为了
if '_new' in name:
    self.alias.append(name[:-4])
再次运行会提示：
AttributeError: 'NetworkStage' object has no attribute 'alias'

**Comment by ahangchen** [comment]
上官网论坛找找解决方案？有结论的话欢迎回来说一声

**Comment by qingshutie** [comment]
@ahangchen 我没有修改ncsdk中的脚本，我修改了训练中使用的 train.prototxt，将conv11 以后的网络带有“_new”的部分删去，得到的prototxt就可以正常使用了

**Comment by qingshutie** [comment]
其实这个问题就是生成prototxt的问题，给的template中就已经带有了“_new”，将template中的example文件改掉就一劳永逸了

**Comment by hacker-wei** [comment]
@ahangchen 你好，请问，您的rank5和rank10是怎么求出来的？
